#!/usr/bin/env bash
# transfers file from our client to a server
# accepts:
#	path to the file to be transfered
#	ip of the server we want to transfer the file to
#	the username scp connects with
#	the path to the SSH private key that the scp uses

if (( $# < 4 ))
then
	echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
else
	scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi
