#!/usr/bin/env bash
# installs nginx on web server

sudo apt-get -y update
sudo apt-get -y install nginx

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html


printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

     location /redirect_me {
     	return 301 https://example.com;
     }

     error_page 404 /404.html;
     location /404 {
	root /etc/nginx/html;
	internal;
     }
}
" > /etc/nginx/sites-available/default

service nginx restart
