#!/usr/bin/env bash

apt-get update -y
apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get install -y haproxy=2.6.\*


echo "ENABLED=1" >> /etc/default/haproxy

printf %s "
frontend dagim.tech-front
	bind	*:80
	mode	http
	option	http-keep-alive
	default_backend	dagim.tech-back

backend dagim.tech-back
	mode	http
	balance	roundrobin
	server	77258-web-01 54.237.104.37:80 check
	server	77258-web-02 35.174.176.205:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
