#!/usr/bin/env bash
# Installs, configures, and starts the load balancer

sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get install -y haproxy=2.7.\*


echo "ENABLED=1" >> /etc/default/haproxy

mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
	log 127.0.0.1 local0 notice
	maxconn 2000
	user haproxy
	group haproxy

defaults
	log     global
	mode    http
	option  httplog
	option  dontlognull
	retries 3
	option redispatch
	timeout connect 10000
	timeout client  50000
	timeout server  50000

frontend alx-frontend
	bind *:80
	mode http
	default_backend alx-backend

backend alx-backend
	balance roundrobin
	server 77258-web-01 54.237.104.37:80 check
	server 77258-web-02 52.91.160.57:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
