#!/usr/bin/env bash
# Installs, configures, and starts the load balancer

sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get install -y haproxy=2.6.\*


echo "ENABLED=1" >> /etc/default/haproxy

mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
	log 127.0.0.1 local0 notice
	maxconn 2000
	user haproxy
	group haproxy

defaults
	log     global
	mode    http
	option  httplog
	option  dontlognull
	retries 3
	option redispatch
	timeout connect  5000
	timeout client  10000
	timeout server  10000

listen alx
	bind *:80
	mode http
	stats enable
	stats uri /haproxy?stats
	balance roundrobin
	option httpclose
	option forwardfor
	server 77258-web-01 54.237.104.37:80 check
	server 77258-web-02 52.91.160.57:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
