#!/usr/bin/env bash
# configure nginx to run and listen on port 80 of all the server's active ipv4 ips
sed 's/ ipv6only=on//g' -i /etc/nginx/sites-available/default
sudo ln -fs /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
