#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid
while 'true'; do
	trap "echo Y U no love me?!; break" SIGINT
	trap "echo I hate the kill command; rm /var/run/myscript.pid; break" SIGTERM
	trap "sudo rm /var/run/myscript.pid; break" SIGQUIT
	echo "To infinity and beyond"
	sleep 2
done
