#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

function rm_myscript()
{
	rm /var/run/myscript.pid
	exit
}

echo $$ > /var/run/myscript.pid
while 'true'; do
	trap "echo Y U no love me?!" SIGINT
	trap "echo I hate the kill command; rm_myscript" SIGTERM
	trap rm_myscript SIGQUIT
	echo "To infinity and beyond"
	sleep 2
done
