#!/usr/bin/env bash
# a script that displays to infinity and beyond indefinetly
# with a sleep 2 in between each iteration
# I am invincibel!!! when receiving SIGTERT

while 'true'; do
	trap "echo I am invincible!!!" SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
