#!/usr/bin/env bash
# a script that displays the content of the file /etc/passwd.
# it displays only:
# username
# user id
# Home directory path for the user

while read -r line
do
	echo "$line" | cut -d ":" -f1,2,3
done < "/etc/passwd"
