#!/usr/bin/env bash
# a script that groups visitors by IP and HTTP status code, and displays this data.
# format: OCCURENCE_NUMBER IP HTTP_CODE

awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort
