#!/usr/bin/env bash
# script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed 

files=$(ls)
for f in $files
do
	echo "$f" | cut -d '-' -f2
done
